name: Publish Docker image to ECR and deploy to EKS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Install aws-cli
        run: |
          python --version
          pip install awscli --upgrade
          aws --version
